---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

# Install Node.js
- name: "Install Node.js"
  become: yes
  apt:
    name: nodejs
    state: present

# Install NPM
- name: "Install NPM"
  become: yes
  apt:
    name: npm
    state: present

# Install PM2
- name: "Install PM2"
  become: yes
  npm:
    name: pm2
    global: yes
